worker_processes 1;

events {
    worker_connections 1024;
}

http {
    # Define o caminho para a pasta /lua do projeto
    lua_package_path "$prefix/lua/?.lua;;";

    # Redireciona arquivos temporários para dentro da pasta logs/
    client_body_temp_path logs/client_body_temp;
    proxy_temp_path       logs/proxy_temp;
    fastcgi_temp_path     logs/fastcgi_temp;
    scgi_temp_path        logs/scgi_temp;
    uwsgi_temp_path       logs/uwsgi_temp;

    server {
        listen 8080;
        default_type application/json;

        location / {
            content_by_lua_file lua/controllers/hello.lua;
        }
    }
}